--- # Open the ProfanityFilter CI at https://poggit.pmmp.io/ci/ReinfyTeam/ProfanityFilter
build-by-default: true
branches:
- build
projects:
  ProfanityFilter:
    path: ""
    icon: "ProfanityFilter.png" 
    lint: false
...
