---
name: ProfanityFilter
version: 0.1.4
main: ReinfyTeam\ProfanityFilter\Loader
api:
- 5.0.0
description: "A best profanity filter for pocketmine. Controls hate speech and blocks bad words in certain on the chat."
website: "https://github.com/ReinfyTeam/ProfanityFilter"
author: "ReinfyTeam"
authors: ["NhanAZ","xqwtxon","xVoiqMC"]
...
