---
name: ProfanityFilter
<<<<<<< HEAD
version: 1.0.0
main: ReinfyTeam\ProfanityFilter\Loader
api: 
- 4.0.0
- 5.0.0
src-namespace-prefix: ReinfyTeam\ProfanityFilter
=======
version: 0.1.0-BETA
main: ReinfyTeam\ProfanityFilter\Loader
api: [5.0.0]
>>>>>>> 5db9edb693762ec361579ba6997c376955254b63
description: "A best profanity filter for pocketmine. Controls hate speech and blocks bad words in certain on the chat."
website: "https://github.com/ReinfyTeam/ProfanityFilter"
author: "ReinfyTeam"
authors: ["NhanAZ","xqwtxon","xVoiqMC"]
...
