---
name: ProfanityFilter
version: 0.0.7
main: ReinfyTeam\ProfanityFilter\Loader
api: 4.0.0
src-namespace-prefix: ReinfyTeam\ProfanityFilter
description: "A best profanity filter for pocketmine. Controls hate speech and blocks bad words in certain on the chat."
website: "https://github.com/ReinfyTeam/ProfanityFilter"
author: "ReinfyTeam"
authors: ["NhanAZ","xqwtxon","xVoiqMC"]
...
